코드 리뷰 PR
fakerdeft/CoverFlow-BE pull request #1
Opened 2024-02-27 16:05 UTC by fakerdeft

코드리뷰 잘 부탁드립니다...

2024-02-27 18:14 UTC, VSFe requested changes
맛보기 삼아? 가볍게 작성해 보았습니다.
너무 많은 리뷰가 한방에 달리면 당황스러울 것 같아, 우선 반영할 시간을 드리는게 좀 더 나을 것 같아요.

(+ final을 너무 많이 붙일 필요는 없습니다 ㅎㅎ...)

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +            @RequestParam(defaultValue = "name", value = "name") @Valid final String name
`@Valid` 를 쓰기엔, 조건이 뭔지 전혀 명시가 되어 있지 않아요.
(여기서는 `@NotEmpty` 같은 것들을 고려할 수 있겠죠.)

전체적인 Validation 로직에 대한 재작성이 필요해보입니다.

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +            @RequestBody @Valid final SaveCompanyRequest saveCompanyRequest
이런 객체에 대해서 `@Valid`를 사용하고 싶다면, 해당 객체의 필드 각각에 대해서 원하는 Validation Annotation을 삽입해야 합니다.

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +    public ResponseEntity<ResponseHandler<Void>> updateNickname(
`updateNickname` 이라고 한다면 뭔가 사용자의 정보를 수정하는 것 같아요.

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +                .body(ResponseHandler.<Void>builder()
전달할 데이터가 없다면 HTTP 204 (NO_CONTENT) 가 좀 더 자연스럽습니다.

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +        return ResponseEntity.ok()
POST 메서드를 통해 데이터를 업로드 한다면 HTTP 201 (CREATED) 가 좀 더 자연스러울 것 같습니다.

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +            @PathVariable @Valid final Long companyId
companyId는 nullable 하지 않을 것 같아요.
```java
@PathVariable @Positive long companyId
```

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/enquiry/application/EnquiryService.java
> +@Transactional(readOnly = true)
제거

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/enquiry/application/EnquiryService.java
> +        final Pageable pageable = PageRequest.of(pageNo, 10, Sort.by(criterion).descending());
전체적으로 반복적인 작업들이 많네요.
이를 공통화 시킬 수 있는 방법은 없을까요?

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/enquiry/application/EnquiryService.java
> +                .status("등록")
enum

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/enquiry/application/EnquiryService.java
> +    public void saveEnquiry(
readonly 가 아니죠?

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/enquiry/exception/EnquiryException.java
> +            super(String.format("문의가 존재하지 않습니다. - request info { memberId : %s }", memberId));
저라면 그냥...

```java
public EnquiryNotFoundException(Object data) {
    super(String.format("문의가 존재하지 않습니다. - request info => %s", data));
}

로 통일할 것 같아요.
```

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/enquiry/infrastructure/EnquiryRepository.java
> +    @Query("SELECT e " +
생각해보니까, Java 17은 Multiline String이 됩니다.

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/enquiry/infrastructure/EnquiryRepository.java
> +            "AND e.status != '삭제'")
- 이후에도 "삭제"라는 키워드를 계속 쓸까요? (혹시나 이름이 변경되진 않을까요? 그렇다면, 모든 컬럼의 정보를 다 바꿔야 하지 않을까요?)
- 서비스가 외국으로 확대된다고 했을 때, 해당 키워드를 유지하는게 바람직 할까요?

가능하면 DB에 저장될 때는 Ordinal 정보나 영어 키워드로 저장하되, 자바 코드에선 Enum으로 관리하면서 주석이나 필드에 한글 내용을 넣는게 좀 더 좋을 것 같습니다.

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/enquiry/presentation/EnquiryController.java
> +            @RequestParam(defaultValue = "0", value = "pageNo") @Valid final int pageNo,
마찬가지로, value는 모두 제거해 주세요.

2024-02-27 18:14 UTC, VSFe commented on src/main/java/com/coverflow/enquiry/presentation/EnquiryController.java
> +    @GetMapping("/find-enquiry")
"가능하다면" REST API의 Path는 최대한 명사로 구성하고, 동작 (find, delete) 등은 REST API의 Method로 판단하도록 하는게 권장되는 API 디자인이에요.

```java
@GetMapping("/enquiry") // 문의 조회
@PostMapping("/enquiry") // 문의 등록
@DeleteMapping("/enquiry") // 문의 삭제
@PutMapping("/enquiry") // 문의 수정, 또는 @PatchMapping("/enquiry")
```

2024-02-28 01:42 UTC, fakerdeft reviewed
부족한 부분이나 개선해야 될 부분들을 잘 짚어주셔서 정말 정말 감사합니다. 해당 리뷰들을 바탕으로 꼭 개선해 볼게요!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/company/infrastructure/CompanyRepository.java
> +    Optional<Page<Company>> findAllByNameStartingWithAndStatus(
> 이후에는 인덱스에 대한 고려도 해 주세요. 해당 쿼리는 (name, status) 와 같은 방식의 인덱스 생성이 필요해 보여요.

제가 인덱스 개념을 몰랐습니다. 피드백 주신대로 한 번 인덱스 개념 찾아보고 필요성을 느껴보겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +            @RequestParam(defaultValue = "name", value = "name") @Valid final String name
> value는 전부 생략 가능합니다.

그렇다면 최대한 지워보겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +            @RequestParam(defaultValue = "name", value = "name") @Valid final String name
> `@Valid` 를 쓰기엔, 조건이 뭔지 전혀 명시가 되어 있지 않아요. (여기서는 `@NotEmpty` 같은 것들을 고려할 수 있겠죠.)
> 
> 전체적인 Validation 로직에 대한 재작성이 필요해보입니다.

`@Valid`를 그냥 단순히 무턱대고 사용했던 것 같습니다. 유효성 검사 로직을 다시 알아보고 구성해 볼게요!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +                        .message("자동 완성 검색에 성공했습니다.")
> 어차피 저희는 메시지를 그렇게 잘 보지 않습니다. (특히 오류가 발생하지 않은 경우엔 더더욱요)

아 어차피 상태코드가 전달되어서 그런 것인가요? 그렇다면 메시지에 들어가는 노력을 줄이겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +            @PathVariable @Valid final Long companyId
> companyId는 nullable 하지 않을 것 같아요.
> 
> ```java
> @PathVariable @Positive long companyId
> ```

1. nullable에 대한 파라미터는 원시 타입 적용하겠습니다!
2. `@Positive` 애노테이션은 처음 봤습니다. 알아보고 적용해 보겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +            @RequestBody @Valid final SaveCompanyRequest saveCompanyRequest
> 이런 객체에 대해서 `@Valid`를 사용하고 싶다면, 해당 객체의 필드 각각에 대해서 원하는 Validation Annotation을 삽입해야 합니다.

`@Valid` 같은 유효성 검증 애노테이션에 대해서 좀 더 알아보고 적재적소에 적용하겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +        return ResponseEntity.ok()
> POST 메서드를 통해 데이터를 업로드 한다면 HTTP 201 (CREATED) 가 좀 더 자연스러울 것 같습니다.

평소에 성공 응답 코드를 좀 단순하게 200으로만 보내려고 했던 것 같습니다. 좀 더 목적에 맞는 코드들을 다양하게 사용하겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +    public ResponseEntity<ResponseHandler<Void>> updateNickname(
> `updateNickname` 이라고 한다면 뭔가 사용자의 정보를 수정하는 것 같아요.

열심히 다른 클래스에서 복붙하고 자세히 검사하지 않은 것이 티가 났네요...꼭 다시 검토해서 수정하겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/company/presentation/CompanyController.java
> +                .body(ResponseHandler.<Void>builder()
> 전달할 데이터가 없다면 HTTP 204 (NO_CONTENT) 가 좀 더 자연스럽습니다.

넵 목적에 맞는 응답 코드를 사용하겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/enquiry/application/EnquiryService.java
> +@Transactional(readOnly = true)
> 제거

네 지우겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/enquiry/application/EnquiryService.java
> +        final Pageable pageable = PageRequest.of(pageNo, 10, Sort.by(criterion).descending());
> 전체적으로 반복적인 작업들이 많네요. 이를 공통화 시킬 수 있는 방법은 없을까요?

공통 기능을 분리해서 따로 메서드로 만들면 될 것 같습니다 바꿔보겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/enquiry/application/EnquiryService.java
> +    public void saveEnquiry(
> readonly 가 아니죠?

넵 트랜잭션 메서드 단위에서 붙이겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/enquiry/application/EnquiryService.java
> +                .status("등록")
> enum

상태는 enum 클래스로 만들겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/enquiry/exception/EnquiryException.java
> +            super(String.format("문의가 존재하지 않습니다. - request info { memberId : %s }", memberId));
> 저라면 그냥...
> 
> ```java
> public EnquiryNotFoundException(Object data) {
>     super(String.format("문의가 존재하지 않습니다. - request info => %s", data));
> }
> 
> 로 통일할 것 같아요.
> ```

아하 상위 타입으로 묶어버리는 좋은 방법이 있었네요 감사합니다!!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/enquiry/infrastructure/EnquiryRepository.java
> +    @Query("SELECT e " +
> 생각해보니까, Java 17은 Multiline String이 됩니다.

아하 그렇다면 쿼리문도 멀티라인 스트링으로 전면 수정해 보겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/enquiry/infrastructure/EnquiryRepository.java
> +            "AND e.status != '삭제'")
> * 이후에도 "삭제"라는 키워드를 계속 쓸까요? (혹시나 이름이 변경되진 않을까요? 그렇다면, 모든 컬럼의 정보를 다 바꿔야 하지 않을까요?)
> * 서비스가 외국으로 확대된다고 했을 때, 해당 키워드를 유지하는게 바람직 할까요?
> 
> 가능하면 DB에 저장될 때는 Ordinal 정보나 영어 키워드로 저장하되, 자바 코드에선 Enum으로 관리하면서 주석이나 필드에 한글 내용을 넣는게 좀 더 좋을 것 같습니다.

1. DB에 들어갈 때는 영어 키워드를
2. 자바 코드에선 주석 같은 것으로 한글 관리를
하도록 하겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/enquiry/presentation/EnquiryController.java
> +    @GetMapping("/find-enquiry")
> "가능하다면" REST API의 Path는 최대한 명사로 구성하고, 동작 (find, delete) 등은 REST API의 Method로 판단하도록 하는게 권장되는 API 디자인이에요.
> 
> ```java
> @GetMapping("/enquiry") // 문의 조회
> @PostMapping("/enquiry") // 문의 등록
> @DeleteMapping("/enquiry") // 문의 삭제
> @PutMapping("/enquiry") // 문의 수정, 또는 @PatchMapping("/enquiry")
> ```

아하... 다시 수정해서 이런 방향으로 API들을 만들겠습니다!

2024-02-28 01:42 UTC, fakerdeft commented on src/main/java/com/coverflow/enquiry/presentation/EnquiryController.java
> +            @RequestParam(defaultValue = "0", value = "pageNo") @Valid final int pageNo,
> 마찬가지로, value는 모두 제거해 주세요.

네 알겠습니다!!

2024-02-28 01:47 UTC, fakerdeft commented
> 맛보기 삼아? 가볍게 작성해 보았습니다. 너무 많은 리뷰가 한방에 달리면 당황스러울 것 같아, 우선 반영할 시간을 드리는게 좀 더 나을 것 같아요.
> 
> (+ final을 너무 많이 붙일 필요는 없습니다 ㅎㅎ...)

1. 그렇다면 final을 파라미터 단에서만 사용하도록 하겠습니다!

너무 너무 감사합니다 보초님! 여태 살면서 제 코드를 리뷰해 주는 사람은 없었습니다. 그런데 좋은 기회로 처음부터 완전 고수님에게 받게 되어서 너무 감사할 따름입니다. 피드백 주신 대로 이번 주 내내 부족하거나 새로운 것들에 대해 공부하면서 리팩토링 진행하겠습니다!

2024-03-07 14:22 UTC, merged